# basic config
alg: fedbuff
suffix: default
device: 0
dataset: cifar10
model: cnn

# federated config
total_num: 100
sr: 0.2
rnd: 1000
test_gap: 1

# local training config
bs: 64
epoch: 1
lr: 0.001
gamma: 0.99

decay: 0.3
delay: 5
delay_rate: 0.3

k: 20
etag: 1.5
alpha: 0.3
